### ISSUE TITLE
pdb2glycam/vina_atom_data.hpp is not included in the repo

### ISSUE THREAD

**Issue by gitoliver** [yaox0609/glycomimetics#1]
Can't compile the code without pdb2glycam/vina_atom_data.hpp

**Comment by gitoliver** [comment]
Despite the commit message of the recent push, this file is still not present in the repo
also this one is missing too:
main.cpp:19:10: fatal error: ../../pdb2glycam/vina_bond_by_distance_for_pdb.hpp: No such file or directory
   19 | #include "../../pdb2glycam/vina_bond_by_distance_for_pdb.hpp"

I would suggest that you download/clone the repo somewhere else on your machine and fix all the broken paths so that it compiles and runs tests. Note that you can change:
"../../includes/gmml.hpp"
to
"includes/gmml.hpp"
and because you have this in the compile command:
 g++ -std=c++17 **-I $GEMSHOME/gmml/**
 it will find the gmml.hpp file.

**Comment by yaox0609** [comment]
Hi Oli:

I just tagged you on Slack explaining this issue. My next push will add pdb2glycam, but I'm concerned with boost. The boost path in my g++ compile commands reflect my environment, but not yours.

If you can change those paths to match your environment, I can push and you will be able to get that file.

Yao
________________________________
From: Oliver ***@***.***>
Sent: Monday, May 2, 2022 11:10
To: yaox0609/glycomimetics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yaox0609/glycomimetics] pdb2glycam/vina_atom_data.hpp is not included in the repo (Issue #1)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]


Can't compile the code without pdb2glycam/vina_atom_data.hpp
